### ISSUE TITLE
Null reference used for synchronization (monitor-enter)

### ISSUE THREAD

**Issue by mnewlive** [mnewlive/make-it#26]
When I turn off my Internet connection and log out from Firebase app, I can't return my app.

Also get next error:

> 2019-11-05 20:26:19.364 5593-5611/com.mandarine.target_list E/System: Uncaught exception thrown by finalizer 2019-11-05 20:26:19.365 5593-5611/com.mandarine.target_list E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter) at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053) at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252) at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239) at java.lang.Daemons$Daemon.run(Daemons.java:105) at java.lang.Thread.run(Thread.java:764)

It only happens when I turn off the Internet.

**Comment by mnewlive** [comment]
SO discussion is [here<<](https://stackoverflow.com/questions/58717395/null-reference-used-for-synchronization-monitor-enter)

**Comment by mnewlive** [comment]
Not relevant.

**Comment by MahmoudEraqi95** [comment]
What was the problem?

**Comment by mnewlive** [comment]
> What was the problem?

thx, but not relevant right now ;)
